# Target ABI should be one of: armeabi, armeabi-v7a, x86
# mips ABI is not supported (no native compiler)
ABI = gnueabihf

# Which Android platform to use
TARGET_PLATFORM = android-14

# Path of the Android NDK
TARGET_NDK = ${OPAM_PREFIX}/lib/android-ndk

TARGET_TOOLCHAIN_PATH = /usr/bin

# OCaml sources (will be copied)
OCAML_SRC = ${OPAM_PREFIX}/lib/ocaml-src

# Where the cross-compiler libraries are installed
TARGET_PREFIX = ${OPAM_PREFIX}/$(HOST_ARCH)

# Where the cross-compiler binaries are installed
TARGET_BINDIR = ${OPAM_PREFIX}/bin

OPAM_PREFIX := $(shell opam config var prefix)
